name: grapher_annotation
description: Annotation package for 'grapher_builder' package. For generating GraphQL based on dart code models.
version: 0.5.0
resolution: workspace

repository: https://github.com/iadept/grapher/

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  gql: ^1.0.0
  graphql: ^5.0.0
  meta: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
