extend type Query {
    categories(input: SelectCategoryInput!): [Category!]!
    items(input: SelectItemInput!): [Item!]!

    brands(input: SelectBrandsInput!): [Brand!]!
}

extend type Mutation {
    updateItem(input: UpdateItemInput!): Item! 
}

type Category {
    id: ID!
    name: String!
}

input SelectCategoryInput {
    search: String
}

type Item {
    id: ID!
    createdAt: Timestamp!
    name: String!
    description: String
    count: Int!
    price: Double!
    status: ItemStatus!
    sale: Boolean
}

enum ItemStatus {
    draft,
    public,
    promo
}

input SelectItemInput {
    id: ID
}

input UpdateItemInput {
    id: ID!
    name: String
    description: String
    count: Int
    status: ItemStatus
}

type Brand {
    id: ID!
    name: String!
    popular(input: SelectPopularityInRegionInput!): Boolean!
}

input SelectBrandsInput {
    ids: [ID!]
}

input SelectPopularityInRegionInput {
    countryCode: ID! 
}

# Union example

type ItemDetails {
    details: Details
}

union Details = WashingMachineDetails | RefrigeratorDetails | OvenDetails

type WashingMachineDetails {
    loadCapacity: Int!
    spinSpeed: Int!
}

type RefrigeratorDetails {
    volume: Int!
    hasFreezer: Boolean!
}

type OvenDetails {
    power: Int!
    hasConvection: Boolean!
}